apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
data:
  loki.yaml: |
    auth_enabled: {{ .Values.logging.loki.config.auth_enabled }}
    server:
      http_listen_port: 3100
    limits_config:
      enforce_metric_name: false
    ingester:
      lifecycler:
        ring:
          store: {{ .Values.logging.loki.config.ingester.lifecycler.ring.store }}
          replication_factor: {{ .Values.logging.loki.config.ingester.lifecycler.ring.replication_factor }}
      chunk_idle_period: 15m

{{- if .Values.logging.loki.config.schema_configs }}
    schema_config:
      configs:
  {{- range .Values.logging.loki.config.schema_configs }}
      - from: {{ .from }}
        store: {{ .store }}
        object_store: {{ .object_store }}
        schema: {{ .schema }}
        index:
          prefix: {{ .index.prefix }}
          period: {{ .index.period }}
  {{- end -}}
{{- end -}}

{{- if .Values.logging.loki.config.storage_configs }}
    storage_config:
  {{- range .Values.logging.loki.config.storage_configs }}
      {{ .name }}:
        directory: {{ .directory }}
  {{- end -}}
{{- end -}}
